from __future__ import annotations

from typing import Protocol

from ..types import ItemProfile, SimilarUserProfile


class RetrievalTools(Protocol):
    def get_similar_users(self, user_id: str, n: int) -> list[SimilarUserProfile]: ...
    def get_relevant_items(self, user_id: str, query: str, n: int) -> list[ItemProfile]: ...
    def retrieve_by_query(self, query: str, k: int) -> list[ItemProfile]: ...
    def retrieve_by_item(self, item_id: str, k: int) -> list[ItemProfile]: ...
